import { Personaje, Lugar, Faccion } from "@/types/fichas";
import { ProyectoLiterario, Capitulo } from "@/types/editor";
import { AlertaConsistencia } from "@/types/ai";

export const MOCK_FACCIONES: Faccion[] = [
  {
    id: "fac-1",
    nombre: "La Orden del Éter Silente",
    lema: "En el silencio reside el equilibrio primordial.",
    tipoAlineamiento: "Orden",
    lideres: ["Archimaestre Vaelen", "Dama Seraphina"],
    sedePrincipal: "Bastión de Agujas, Ciudad Alta",
    ideologiaObjetivos: "Monopolizar y regular el uso de reliquias arcanas para prevenir una segunda Fractura del Velo.",
    recursosPoder: "Gran biblioteca arcana, regimiento de inquisidores de velo y bóvedas subterráneas de éter.",
    aliados: ["Guardia de la Corona"],
    enemigos: ["El Culto de las Sombras Gemelas"],
    creadoEn: "2026-01-10",
    actualizadoEn: "2026-03-01",
  },
  {
    id: "fac-2",
    nombre: "Gremio de la Ceniza Roja",
    lema: "El oro no tiene lealtades; nosotros tampoco.",
    tipoAlineamiento: "Gremial",
    lideres: ["Jaxen el Tuerto"],
    sedePrincipal: "Los Bajos Fondos de Puerto Marea",
    ideologiaObjetivos: "Controlar el contrabando de artefactos antiguos y mantener su autonomía frente a las leyes reales.",
    recursosPoder: "Red clandestina de informantes, astilleros encubiertos y asesinos de alquiler.",
    aliados: [],
    enemigos: ["La Orden del Éter Silente", "Guardia de la Corona"],
    creadoEn: "2026-01-15",
    actualizadoEn: "2026-02-28",
  },
];

export const MOCK_LUGARES: Lugar[] = [
  {
    id: "lug-1",
    nombre: "Ciudadela de Valdoris",
    tipo: "Ciudad",
    descripcion: "Metrópolis de torres de mármol blanco y puentes colgantes suspendidos entre acantilados frente al Mar del Norte.",
    climaAmbiente: "Costero, ventoso, niebla espesa al amanecer.",
    facciónControladora: "La Orden del Éter Silente",
    puntosInteres: ["El Gran Faro de Cristal", "La Bóveda Hundida", "Distrito de los Alquimistas"],
    eventosHistoricos: ["Firma del Tratado de las Tres Lunas (hace 80 años)", "El Asedio de las Cenizas"],
    notasSensoriales: "Aroma penetrante a salitre, humo de incienso de jazmín en los templos y eco constante de campanas de bronce.",
    creadoEn: "2026-01-12",
    actualizadoEn: "2026-02-14",
  },
  {
    id: "lug-2",
    nombre: "El Bosque de los Susurros Pálidos",
    tipo: "Paraje Natural",
    descripcion: "Antiguo bosque de secuoyas petrificadas donde las leyes del tiempo y el sonido parecen distorsionarse.",
    climaAmbiente: "Húmedo, perpetuamente crepuscular, frío cortante.",
    facciónControladora: "Neutral / Territorio Salvaje",
    puntosInteres: ["El Árbol sin Raíces", "Círculo de Menhires Rotos"],
    eventosHistoricos: ["Desaparición de la Séptima Legión Real"],
    notasSensoriales: "Silencio sepulcral roto por crujidos de ramas sin viento; olor a tierra mojada y ozono.",
    creadoEn: "2026-01-20",
    actualizadoEn: "2026-03-02",
  },
  {
    id: "lug-3",
    nombre: "Taberna El Caldero Hundido",
    tipo: "Taberna / Posada",
    ubicacionPadre: "Puerto Marea",
    descripcion: "Posada excavada en el casco de un antiguo galeón encallado bajo los muelles de madera.",
    climaAmbiente: "Cálido, saturado de humo de tabaco de pipa y vapor de guisos picantes.",
    facciónControladora: "Gremio de la Ceniza Roja",
    puntosInteres: ["Mesa privada del capitán detrás de la chimenea", "Cava clandestina"],
    eventosHistoricos: ["Pacto secreto entre Jaxen y el Príncipe Traidor"],
    notasSensoriales: "Olor a cerveza rancia, madera podrida y grasa asada.",
    creadoEn: "2026-02-05",
    actualizadoEn: "2026-02-25",
  },
];

export const MOCK_PERSONAJES: Personaje[] = [
  {
    id: "per-1",
    nombre: "Valeria Thorne",
    alias: "La Tejedora de Cenizas",
    rol: "Protagonista",
    edad: "26 años",
    ocupacion: "Cartógrafa arcana y ex-inquisidora rebelde",
    facciónId: "fac-1",
    facciónNombre: "La Orden del Éter Silente (desertora)",
    apariencia: "Estatura media, ojos color ámbar penetrante, cicatriz fina cruzando su ceja izquierda, viste abrigo de cuero deshilachado con runas bordadas con hilo plateado.",
    personalidad: "Observadora, pragmática, sarcástica cuando está bajo estrés. Le cuesta delegar y guarda una culpa profunda por la muerte de su hermano.",
    trasfondo: "Criada dentro de la Orden de los Éteres, descubrió que los artefactos que confiscaban no eran destruidos sino utilizados para alimentar una máquina secreta bajo la Ciudadela.",
    objetivos: "Localizar el Compás del Alba antes de que la Orden lo active, y rescatar a su mentor encarcelado.",
    miedosDebilidades: "Claustrofobia provocada por su encierro de niña en las mazmorras de Valdoris; desconfianza crónica.",
    relaciones: [
      {
        personajeId: "per-2",
        nombrePersonaje: "Lord Corvus Van-Halen",
        tipo: "Enemigo",
        descripcion: "Antiguo superior en la Orden y ahora su implacable perseguidor.",
      },
      {
        personajeId: "per-3",
        nombrePersonaje: "Gaelen el Erudito",
        tipo: "Aliado",
        descripcion: "Amigo de la infancia y traductor de pergaminos antiguos.",
      },
    ],
    creadoEn: "2026-01-11",
    actualizadoEn: "2026-03-04",
  },
  {
    id: "per-2",
    nombre: "Lord Corvus Van-Halen",
    alias: "El Ojo Inmutable",
    rol: "Antagonista",
    edad: "48 años",
    ocupacion: "Comandante General del Bastión de Agujas",
    facciónId: "fac-1",
    facciónNombre: "La Orden del Éter Silente",
    apariencia: "Alto, complexión imponente, cabellos canos peinados hacia atrás, armadura ceremonial pavonada en negro con el emblema de la Orden fundido en oro mate.",
    personalidad: "Meticuloso, devoto de la ley ciega, carente de empatía aparente pero guiado por un ideal retorcido de paz a través del orden absoluto.",
    trasfondo: "Veterano de las Guerras del Velo, perdió a su familia a manos de hechiceros renegados, lo que cimentó su odio hacia cualquier uso de magia no regulada.",
    objetivos: "Capturar a Valeria y recuperar el Fragmento de Éter antes de la Luna Nueva.",
    miedosDebilidades: "Terror a la pérdida de control; sufre de un deterioro físico progresivo que oculta bajo su armadura.",
    relaciones: [
      {
        personajeId: "per-1",
        nombrePersonaje: "Valeria Thorne",
        tipo: "Rival",
        descripcion: "La consideraba su pupila más brillante antes de su traición.",
      },
    ],
    creadoEn: "2026-01-14",
    actualizadoEn: "2026-02-26",
  },
  {
    id: "per-3",
    nombre: "Gaelen de la Ribera",
    alias: "El Sabio Descalzo",
    rol: "Secundario",
    edad: "31 años",
    ocupacion: "Archivero independiente y alquimista botánico",
    apariencia: "Delgado, hombros encorvados por pasar años sobre escritorios, anteojos redondos de latón, túnica manchada de tinta y polvo vegetal.",
    personalidad: "Curioso hasta la imprudencia, bondadoso, nervioso ante el conflicto físico.",
    trasfondo: "Expulsado de la Gran Academia por cuestionar los dogmas oficiales sobre la edad del mundo.",
    objetivos: "Catalogar las especies botánicas del Bosque de los Susurros.",
    relaciones: [
      {
        personajeId: "per-1",
        nombrePersonaje: "Valeria Thorne",
        tipo: "Aliado",
        descripcion: "Le proporciona refugio seguro y descifra las coordenadas de sus mapas.",
      },
    ],
    creadoEn: "2026-01-18",
    actualizadoEn: "2026-02-20",
  },
];

export const MOCK_CAPITULOS: Capitulo[] = [
  {
    id: "cap-1",
    numero: 1,
    titulo: "La Grieta en el Mármol",
    sinopsis: "Valeria descubre que la Orden está drenando las bóvedas subterráneas y debe huir de la Ciudadela antes del toque de queda.",
    estado: "Revisado",
    creadoEn: "2026-02-01",
    actualizadoEn: "2026-02-20",
    escenas: [
      {
        id: "esc-1-1",
        capituloId: "cap-1",
        numero: 1,
        titulo: "El Salón de los Códices Prohibidos",
        contenido: "La cera de las velas parpadeaba contra los lomos de cuero curtido. Valeria contuvo la respiración al girar el cilindro de bronce. En su interior, el pergamino no contenía leyes, sino las firmas de defunción de los alquimistas purgados. Los pasos pesados de los guardias resonaron en el pasillo norte.",
        lugarId: "lug-1",
        lugarNombre: "Ciudadela de Valdoris",
        tiempoNarrativo: "Noche de la Luna Menguante, 23:40 hs",
        personajesInvolucradosIds: ["per-1"],
        conteoPalabras: 64,
        estado: "Completada",
        creadoEn: "2026-02-01",
        actualizadoEn: "2026-02-05",
      },
      {
        id: "esc-1-2",
        capituloId: "cap-1",
        numero: 2,
        titulo: "Escape por los Techos Bajos",
        contenido: "El viento salado golpeó su rostro cuando saltó hacia el tejado de tejas mojadas. A lo lejos, la campana de alarma del Bastión comenzó a tañer. Lord Corvus ya estaba apostando centinelas en las compuertas del muelle.",
        lugarId: "lug-1",
        lugarNombre: "Ciudadela de Valdoris",
        tiempoNarrativo: "Misma noche, 00:15 hs",
        personajesInvolucradosIds: ["per-1", "per-2"],
        conteoPalabras: 51,
        estado: "Completada",
        creadoEn: "2026-02-06",
        actualizadoEn: "2026-02-10",
      },
    ],
  },
  {
    id: "cap-2",
    numero: 2,
    titulo: "Ecos en la Niebla",
    sinopsis: "Valeria busca refugio en los linderos del Bosque de los Susurros y se reúne con Gaelen para planear la ruta.",
    estado: "En progreso",
    creadoEn: "2026-02-15",
    actualizadoEn: "2026-03-04",
    escenas: [
      {
        id: "esc-2-1",
        capituloId: "cap-2",
        numero: 1,
        titulo: "El Encuentro en el Molino Abandonado",
        contenido: "Gaelen calentaba una infusión de menta silvestre cuando la puerta crujió. Valeria empapada entró con la capucha calada hasta la nariz. Traía el cilindro intacto, pero sus ojos delataban la persecución implacable.",
        lugarId: "lug-2",
        lugarNombre: "El Bosque de los Susurros Pálidos",
        tiempoNarrativo: "Amanecer del día siguiente",
        personajesInvolucradosIds: ["per-1", "per-3"],
        conteoPalabras: 48,
        estado: "Borrador",
        creadoEn: "2026-02-15",
        actualizadoEn: "2026-03-04",
      },
    ],
  },
];

export const MOCK_PROYECTO: ProyectoLiterario = {
  id: "proy-1",
  titulo: "Las Crónicas del Velo Fracturado",
  autor: "Sebastián",
  genero: "Fantasía Oscura / Intriga Arcana",
  descripcion: "En un imperio sostenido por el monopolio mágico, una ex-inquisidora y un grupo de disidentes intentan evitar que una antigua catástrofe vuelva a devorar el continente.",
  objetivoPalabras: 80000,
  capitulos: MOCK_CAPITULOS,
};

export const MOCK_ALERTAS_CONSISTENCIA: AlertaConsistencia[] = [
  {
    id: "alt-1",
    categoria: "Lugar y Distancia",
    severidad: "Crítico",
    titulo: "Conflicto de Ubicación: Lord Corvus",
    descripcion: "Lord Corvus aparece en el Capítulo 1 (Escena 2) apostando centinelas en los muelles de Valdoris a las 00:15 hs, pero el informe de guardia indica que estaba en reunión en el Bastión de Agujas al mismo tiempo.",
    fragmentoAfectado: "Lord Corvus ya estaba apostando centinelas en las compuertas del muelle...",
    sugerenciaResolucion: "Modificar para que sean los oficiales subordinados de Corvus quienes ejecuten la orden, o justificar el uso de un artefacto de proyección astral.",
    entidadesInvolucradas: [
      { tipo: "Personaje", id: "per-2", nombre: "Lord Corvus Van-Halen" },
      { tipo: "Lugar", id: "lug-1", nombre: "Ciudadela de Valdoris" },
    ],
  },
  {
    id: "alt-2",
    categoria: "Línea Temporal",
    severidad: "Advertencia",
    titulo: "Tiempo de Viaje Inconsistente",
    descripcion: "La distancia entre la Ciudadela de Valdoris y el Molino del Bosque de los Susurros requiere al menos dos días a caballo; en el borrador, Valeria llega en pocas horas a pie durante la misma madrugada.",
    sugerenciaResolucion: "Añadir una transición temporal o justificar un atajo por los túneles olvidados de los contrabandistas.",
    entidadesInvolucradas: [
      { tipo: "Personaje", id: "per-1", nombre: "Valeria Thorne" },
      { tipo: "Lugar", id: "lug-2", nombre: "El Bosque de los Susurros Pálidos" },
      { tipo: "Tiempo", nombre: "Transición Cap 1 a Cap 2" },
    ],
  },
  {
    id: "alt-3",
    categoria: "Personalidad o Rasgo",
    severidad: "Sugerencia",
    titulo: "Rasgo de Claustrofobia Omitido",
    descripcion: "En la ficha de Valeria se especifica fobia severa a espacios cerrados, sin embargo en el Capítulo 2 permanece calmada dentro del sótano sin signos de tensión.",
    sugerenciaResolucion: "Incluir una descripción sensorial de su malestar o una reacción física leve para mantener la coherencia del personaje.",
    entidadesInvolucradas: [
      { tipo: "Personaje", id: "per-1", nombre: "Valeria Thorne" },
    ],
  },
];
